server:
  port: 8763

spring:
  application:
    name: service-hi
  mvc:
    static-path-pattern: /
  resources:
    static-locations: classpath:/
  thymeleaf:
    prefix: classpath:/templates
  datasource:
    url: jdbc:mysql://10.10.10.10:3306/LDKJ?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-dialect: true
